### ISSUE TITLE
Was this supposed to be mixed with Zero's latest release?

### ISSUE THREAD

**Issue by xydreen** [JasonInd/ChatGPT-DiscordBot#2]
Was this update supposed to be mixed with Zero's latest release (with ChatGPT not working properly due to cloudflare, and now using GPT-3)?

I ask because you're missing requirements.txt

Anyway, thanks for the hard work!

**Comment by JasonInd** [comment]
I've added a requirements.txt now thanks for pointing out I didn't realise that I hadn't uploaded it, thought it was there already (my bad).
It's not mixed with Zero's release, it is my own version but I have taken inspiration from Zero's project. It uses ChatGPT as revChatGPT has been updated once again so that you can use ChatGPT (they added cloudflare bypass) thus it is not using GPT-3. 
Zero's version has not been updated so I decided to make one myself. Hope this helps!
