### ISSUE TITLE
Online host

### ISSUE THREAD

**Issue by maxilosgundam** [JasonInd/ChatGPT-DiscordBot#4]
Is there a way to somehow integrate this into an independent host like Replit or Docker? Or is the manual verify of the captcha preventing this from doing so?

**Comment by JasonInd** [comment]
You can do it if you have a 2captcha bypass then that gets past the human verification and using your account email and password for the login and pass through 2captcha API key, but that costs money so I don't think it is very suitable as you seem to want to be able to host for free (I'm guessing this is the case from Replit). Otherwise there isn't another way currently.

The reason as to why it uses undetected chromedriver as it is currently free chatGPT allowing as many conversation messages as you would like, not GPT-3 which will use up your API credits. 
So you can switch to use GPT-3 if you'd like (no code will be done by me for GPT-3).
